-- 알림 테이블
CREATE TABLE IF NOT EXISTS NOTIFICATION (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
receiver_id BIGINT NOT NULL,
notification_type ENUM('DEPOSIT', 'WITHDRAWAL', 'COMMENT', 'PARTICIPATION_REQUEST') NOT NULL,
reference_id BIGINT,
actor_id BIGINT,
status ENUM('UNREAD', 'READ') DEFAULT 'UNREAD',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
